# Generated by Django 3.0.5 on 2020-04-30 04:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact_us',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('message', models.TextField(max_length=300)),
            ],
            options={
                'db_table': 'Contact_us',
            },
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('desc', models.TextField(max_length=200)),
                ('address', models.TextField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=12, null=True)),
            ],
            options={
                'db_table': 'Hotel',
            },
        ),
        migrations.CreateModel(
            name='Room_catagories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'Room_catagories',
            },
        ),
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_of_person', models.PositiveIntegerField()),
                ('num_of_rooms', models.PositiveIntegerField()),
                ('catagory_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hrent.Room_catagories')),
                ('hotel_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hrent.Hotel')),
            ],
            options={
                'db_table': 'Rooms',
            },
        ),
        migrations.CreateModel(
            name='Room_image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='pics')),
                ('room_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hrent.Rooms')),
            ],
            options={
                'db_table': 'Room_images',
            },
        ),
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('room_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hrent.Rooms')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Bookings',
            },
        ),
    ]
