# Generated by Django 3.0.5 on 2020-04-30 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hrent', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='hotel',
            table='Hotels',
        ),
    ]
