# Generated by Django 3.0.5 on 2020-04-30 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hrent', '0002_auto_20200430_0437'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='bookings',
            table='Booking',
        ),
        migrations.AlterModelTable(
            name='contact_us',
            table='Contact_u',
        ),
        migrations.AlterModelTable(
            name='hotel',
            table='Hotel',
        ),
        migrations.AlterModelTable(
            name='room_catagories',
            table='Room_catagorie',
        ),
        migrations.AlterModelTable(
            name='room_image',
            table='Room_image',
        ),
        migrations.AlterModelTable(
            name='rooms',
            table='Room',
        ),
    ]
