# Generated by Django 3.0.5 on 2020-04-30 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hrent', '0004_auto_20200430_0449'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room_catagories',
            options={'verbose_name_plural': 'Room_catagories'},
        ),
    ]
