# Generated by Django 3.0.5 on 2020-04-30 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hrent', '0005_auto_20200430_0451'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hotel',
            options={'verbose_name_plural': 'Hotels'},
        ),
    ]
